#!/usr/bin/env python3
"""
Build the "AI, Unplugged" deck from src/ into a single self-contained HTML file.

    python3 build.py              -> index.html       (readable, committed)
    python3 build.py --release    -> dist/index.html  (smaller, gitignored)

Stdlib only, on purpose. The deck must build on a laptop with nothing
installed but Python, the same way it must run with no network.

Directives, usable anywhere in any source file:

    <!--#include css/*.css -->     splice in file(s); globs allowed, sorted
    <!--#base64 assets/mlx.png --> splice in a data: URI for a binary asset

Paths are relative to src/, never to the including file — one rule, no
surprises when a partial moves.

Release mode does only provably-safe things: strip comments and collapse
CSS whitespace to single spaces. It deliberately does NOT touch JavaScript.
Hand-rolling a JS minifier without a parser is how you get an ASI bug that
appears only in the build you present from.
"""

import base64
import mimetypes
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "src"
MAX_DEPTH = 10

INCLUDE = re.compile(r"[ \t]*<!--#include\s+(\S+)\s*-->")
BASE64 = re.compile(r"<!--#base64\s+(\S+)\s*-->")


class BuildError(Exception):
    pass


def resolve(pattern, directive):
    """Glob relative to src/. Empty matches are an error, never a silent no-op."""
    hits = sorted(SRC.glob(pattern))
    if not hits:
        raise BuildError(f"{directive} {pattern!r} matched no files under {SRC}")
    return hits


def expand(text, depth=0):
    if depth > MAX_DEPTH:
        raise BuildError("include nesting too deep — circular #include?")

    def do_base64(m):
        path = resolve(m.group(1), "#base64")[0]
        mime = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
        blob = base64.b64encode(path.read_bytes()).decode("ascii")
        return f"data:{mime};base64,{blob}"

    text = BASE64.sub(do_base64, text)

    def do_include(m):
        parts = [p.read_text().rstrip("\n") for p in resolve(m.group(1), "#include")]
        return expand("\n".join(parts), depth + 1)

    return INCLUDE.sub(do_include, text)


def slim_css(css):
    """Strip comments and collapse whitespace runs to ONE space — outside
    string literals only.

    A single space is legal wherever whitespace was legal, so this cannot
    break `calc(7px * var(--r-scale))` the way punctuation-aware squeezing
    can. Quoted values are copied through untouched, so `content: "  "`, a
    data: URI, or a font name keeps its exact bytes, and a `/*` appearing
    inside a string can no longer be mistaken for a comment.
    """
    out, i, n = [], 0, len(css)

    def space():
        if out and out[-1] != " ":
            out.append(" ")

    while i < n:
        c = css[i]
        if c in "\"'":                                   # string: verbatim
            q, j = c, i + 1
            while j < n:
                if css[j] == "\\":
                    j += 2
                    continue
                if css[j] == q:
                    j += 1
                    break
                j += 1
            out.append(css[i:j])
            i = j
        elif css.startswith("/*", i):                    # comment -> separator
            j = css.find("*/", i + 2)
            i = n if j < 0 else j + 2
            space()
        elif c in " \t\r\n\f":
            while i < n and css[i] in " \t\r\n\f":
                i += 1
            space()
        else:
            out.append(c)
            i += 1
    return "".join(out).strip()


def release(html):
    html = re.sub(
        r"<style>(.*?)</style>",
        lambda m: "<style>" + slim_css(m.group(1)) + "</style>",
        html,
        flags=re.S,
    )
    # Comments only outside <script>; a "-->" inside a JS string would
    # otherwise make the regex eat live code.
    head, sep, tail = html.partition("<script>")
    head = re.sub(r"<!--.*?-->", "", head, flags=re.S)
    return head + sep + tail


def main():
    mode_release = "--release" in sys.argv[1:]
    out = ROOT / ("dist/index.html" if mode_release else "index.html")

    src = SRC / "index.html"
    if not src.exists():
        raise BuildError(f"missing {src}")

    html = expand(src.read_text())
    if mode_release:
        html = release(html)

    banner = (
        "<!-- GENERATED by build.py from src/ — do not edit this file by hand. -->\n"
    )
    html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html)

    kb = len(html.encode()) / 1024
    print(f"{'release' if mode_release else 'debug'} -> {out.relative_to(ROOT)}  "
          f"{kb:.1f} KB  {len(html.splitlines())} lines")


if __name__ == "__main__":
    try:
        main()
    except BuildError as e:
        sys.exit(f"build failed: {e}")
